const { test, expect } = require('@playwright/test')
const { randomUUID } = require('node:crypto')
const AxeBuilder = require('@axe-core/playwright').default

async function registerReader(page, navigate = true) {
  const unique = randomUUID(), name = 'Lector ' + unique.slice(0, 8)
  if (navigate) await page.goto('/register')
  await page.getByLabel('Nombre', { exact: true }).fill(name)
  await page.getByLabel('Correo electrónico').fill('interactions-' + unique + '@example.test')
  await page.getByLabel('Contraseña', { exact: true }).fill('Una lectura de prueba privada 2026')
  await page.getByRole('button', { name: 'Crear cuenta', exact: true }).click()
  await expect(page.getByLabel('Nombre público')).toHaveValue(name)
  return { name, email: 'interactions-' + unique + '@example.test' }
}

async function openReading(page) {
  await page.goto('/article/leer-sin-prisa')
  await expect(page.locator('.article-prose')).toContainText('Encontrar el propio ritmo')
}

test('reader saves, reacts, follows and comments; private libraries persist and changes can be undone', async ({ page }, testInfo) => {
  const requests = [], errors = []
  page.on('pageerror', (error) => errors.push(error.message))
  page.on('request', (request) => { if (request.resourceType() === 'fetch') requests.push(new URL(request.url())) })
  const { name } = await registerReader(page), comment = 'Comentario de verificación ' + randomUUID()
  await openReading(page)
  await page.getByRole('button', { name: 'Guardar publicación', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Quitar guardado', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Me interesa', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Te interesa', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: 'Seguir a Elena Rivas', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Dejar de seguir a Elena Rivas', exact: true })).toBeEnabled()
  await page.getByLabel('Tu comentario', { exact: true }).fill(comment)
  await page.getByRole('button', { name: 'Publicar comentario', exact: true }).click()
  const row = page.locator('.comment-item').filter({ hasText: comment })
  await expect(row).toContainText(name)
  await expect(page.getByRole('button', { name: 'Publicar comentario', exact: true })).toBeDisabled()
  await page.reload()
  await expect(row).toContainText(comment)
  await expect(page.getByRole('button', { name: 'Quitar guardado', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('button', { name: 'Te interesa', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('button', { name: 'Dejar de seguir a Elena Rivas', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.emulateMedia({ reducedMotion: 'reduce' })
  for (const theme of ['light', 'dark']) {
    await page.getByRole('combobox', { name: 'Tema de color' }).selectOption(theme)
    await page.getByRole('heading', { name: /Conversación/ }).scrollIntoViewIfNeeded()
    expect((await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()).violations).toEqual([])
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: testInfo.outputPath('interactions-' + theme + '.png') })
  }
  await page.goto('/account')
  await page.locator('main').getByRole('link', { name: 'Publicaciones guardadas', exact: true }).click()
  await expect(page.locator('.library-item')).toContainText('Leer también es una forma de quedarse.')
  await page.reload()
  await expect(page.locator('.library-item')).toHaveCount(1)
  await page.screenshot({ path: testInfo.outputPath('saved-library.png'), fullPage: true })
  await page.getByRole('button', { name: 'Quitar guardado', exact: true }).click()
  await expect(page.locator('.library-item')).toHaveCount(0)
  await expect(page.locator('main')).toContainText('Todavía no tienes publicaciones guardadas')
  await page.goto('/account/following')
  await expect(page.locator('.library-item')).toContainText('Elena Rivas')
  await page.reload()
  await expect(page.locator('.library-item')).toHaveCount(1)
  await page.getByRole('link', { name: 'Elena Rivas', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Dejar de seguir a Elena Rivas', exact: true })).toBeVisible()
  await page.goto('/account/following')
  await page.getByRole('button', { name: 'Dejar de seguir a Elena Rivas', exact: true }).click()
  await expect(page.locator('.library-item')).toHaveCount(0)
  await openReading(page)
  await expect(page.getByRole('button', { name: 'Guardar publicación', exact: true })).toHaveAttribute('aria-pressed', 'false')
  await expect(page.getByRole('button', { name: 'Seguir a Elena Rivas', exact: true })).toHaveAttribute('aria-pressed', 'false')
  await page.getByRole('button', { name: 'Te interesa', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Me interesa', exact: true })).toBeEnabled()
  await row.getByRole('button', { name: 'Eliminar mi comentario', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Eliminar comentario', exact: true }).click()
  await expect(row).toHaveCount(0)
  await page.reload()
  await expect(row).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Me interesa', exact: true })).toHaveAttribute('aria-pressed', 'false')
  expect(requests.every((address) => address.port === '5173' && address.pathname.startsWith('/api/'))).toBe(true)
  expect(errors).toEqual([])
})

test('comment retry after a lost response is idempotent and unsent text has a keyboard-safe exit guard', async ({ page }) => {
  await registerReader(page)
  await openReading(page)
  const text = 'Respuesta perdida ' + randomUUID(), attempts = []
  let loseResponse = true
  await page.route('**/api/interactions', async (route) => {
    const body = route.request().postDataJSON()
    if (body.operationName !== 'WriteComment') return route.continue()
    attempts.push(body.variables.input.id)
    if (loseResponse) {
      loseResponse = false
      // The real server commits first. Only delivery of that successful response is lost.
      const response = await route.fetch()
      expect((await response.json()).data.addComment.text).toBe(text)
      return route.abort('failed')
    }
    return route.continue()
  })
  await page.getByLabel('Tu comentario', { exact: true }).fill(text)
  await page.getByRole('button', { name: 'Publicar comentario', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Reintentar comentario', exact: true })).toBeEnabled()
  await expect(page.getByLabel('Tu comentario', { exact: true })).toHaveValue(text)
  await page.getByRole('button', { name: 'Reintentar comentario', exact: true }).click()
  const row = page.locator('.comment-item').filter({ hasText: text })
  await expect(row).toHaveCount(1)
  expect(attempts).toHaveLength(2)
  expect(attempts[0]).toBe(attempts[1])
  await page.unroute('**/api/interactions')
  await expect(page.getByLabel('Tu comentario', { exact: true })).toHaveValue('')
  await page.getByLabel('Tu comentario', { exact: true }).fill('Texto todavía sin enviar.')
  await page.locator('.article-page__meta').getByRole('link', { name: 'Elena Rivas' }).click()
  const guard = page.getByRole('dialog', { name: 'Tienes cambios sin guardar' })
  await expect(guard).toBeVisible()
  await expect(guard.getByRole('button', { name: 'Seguir editando' })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(guard).not.toBeVisible()
  await expect(page.getByLabel('Tu comentario', { exact: true })).toHaveValue('Texto todavía sin enviar.')
  await page.getByLabel('Tu comentario', { exact: true }).fill('')
  await page.reload()
  await expect(row).toHaveCount(1)
  await row.getByRole('button', { name: 'Eliminar mi comentario', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Eliminar comentario', exact: true }).click()
  await expect(row).toHaveCount(0)
})

test('visitors are asked to sign in and GraphQL outages do not masquerade as an empty reading', async ({ page }) => {
  await openReading(page)
  await expect(page.getByRole('link', { name: 'Inicia sesión para guardar', exact: true })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Inicia sesión para reaccionar', exact: true })).toBeVisible()
  await expect(page.getByLabel('Tu comentario', { exact: true })).toHaveCount(0)
  await page.getByRole('link', { name: 'Inicia sesión para comentar', exact: true }).click()
  await expect(page).toHaveURL(/\/login\?returnTo=%2Farticle%2Fleer-sin-prisa/)
  for (const path of ['/account/saved', '/account/following']) {
    await page.goto(path)
    await expect(page.getByRole('heading', { name: 'Este espacio es tuyo' })).toBeVisible()
    await expect(page.locator('.library-item')).toHaveCount(0)
  }
  await page.route('**/api/interactions', (route) => route.fulfill({ json: { data: { publication: null }, errors: [{ message: 'Interacciones no disponibles durante esta prueba.', extensions: { code: 'SERVICE_UNAVAILABLE' } }] } }))
  await page.goto('/article/leer-sin-prisa')
  await expect(page.getByRole('alert')).toContainText('Interacciones no disponibles durante esta prueba.')
  await expect(page.locator('.comments-section')).toHaveCount(0)
  await page.unroute('**/api/interactions')
  await page.getByRole('button', { name: 'Reintentar', exact: true }).click()
  await expect(page.locator('.article-prose')).toContainText('Encontrar el propio ritmo')
})

test('a failed private library can retry and changing accounts in the same app never reuses saved state', async ({ page }) => {
  const first = await registerReader(page)
  await openReading(page)
  await page.getByRole('button', { name: 'Guardar publicación', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Quitar guardado', exact: true })).toBeEnabled()
  await page.locator('.site-header').getByRole('link', { name: 'Mi cuenta', exact: true }).click()
  await page.route('**/api/interactions', (route) => {
    if (route.request().postDataJSON().operationName !== 'SavedReading') return route.continue()
    return route.fulfill({ json: { errors: [{ message: 'No se pudo leer tu biblioteca durante esta prueba.', extensions: { code: 'SERVICE_UNAVAILABLE' } }] } })
  })
  await page.locator('main').getByRole('link', { name: 'Publicaciones guardadas', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('No se pudo leer tu biblioteca')
  await expect(page.locator('main')).not.toContainText('Todavía no tienes')
  await page.unroute('**/api/interactions')
  await page.getByRole('button', { name: 'Reintentar', exact: true }).click()
  await expect(page.locator('.library-item')).toHaveCount(1)
  const marker = randomUUID()
  await page.evaluate((value) => { window.otherblocSameDocumentTest = value }, marker)
  await page.locator('main').getByRole('link', { name: 'Mi cuenta', exact: true }).click()
  await page.getByRole('button', { name: 'Cerrar sesión', exact: true }).click()
  await page.getByRole('link', { name: 'Crea una cuenta', exact: true }).click()
  await registerReader(page, false)
  await page.locator('main').getByRole('link', { name: 'Publicaciones guardadas', exact: true }).click()
  await expect(page.locator('main')).toContainText('Todavía no tienes publicaciones guardadas')
  await expect(page.locator('.library-item')).toHaveCount(0)
  await page.getByRole('link', { name: 'otherbloc, inicio', exact: true }).first().click()
  await page.locator('.featured-article .text-link').click()
  await expect(page.getByRole('button', { name: 'Guardar publicación', exact: true })).toHaveAttribute('aria-pressed', 'false')
  expect(await page.evaluate(() => window.otherblocSameDocumentTest)).toBe(marker)
  // Restore the first account only to remove its test-owned saved relation.
  await page.locator('.site-header').getByRole('link', { name: 'Mi cuenta', exact: true }).click()
  await page.getByRole('button', { name: 'Cerrar sesión', exact: true }).click()
  await page.getByLabel('Correo electrónico').fill(first.email)
  await page.getByLabel('Contraseña', { exact: true }).fill('Una lectura de prueba privada 2026')
  await page.getByRole('button', { name: 'Iniciar sesión', exact: true }).click()
  await page.locator('main').getByRole('link', { name: 'Publicaciones guardadas', exact: true }).click()
  await expect(page.locator('.library-item')).toHaveCount(1)
  await page.getByRole('button', { name: 'Quitar guardado', exact: true }).click()
  await expect(page.locator('.library-item')).toHaveCount(0)
})
