const { test, expect } = require('@playwright/test')

test('light initializes before React even for dark devices; toggle persists in header and access', async ({ page }) => {
  await page.emulateMedia({ colorScheme: 'dark', reducedMotion: 'reduce' })
  await page.goto('/')
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  await expect(page.getByRole('combobox', { name: 'Tema de color' })).toHaveCount(0)
  const account = page.locator('.account-access')
  await expect(account).toHaveAttribute('aria-label', 'Iniciar sesión')
  await expect(account.locator('img')).toHaveCount(0)
  await expect(account).toHaveAttribute('href', '/login')
  await page.getByRole('button', { name: 'Activar tema oscuro' }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await page.reload(); await expect(page.getByRole('button', { name: 'Activar tema claro' })).toBeVisible()
  await account.click(); await expect(page).toHaveURL(/\/login$/)
  await page.getByRole('button', { name: 'Activar tema claro' }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  for (const value of ['system', 'invalid']) {
    await page.evaluate((value) => localStorage.setItem('otherbloc-theme', value), value)
    await page.reload(); await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  }
  await page.getByRole('button', { name: 'Activar tema oscuro' }).focus()
  await expect(page.getByRole('button', { name: 'Activar tema oscuro' })).toHaveCSS('outline-style', 'solid')
})

test('search field has one visible focus ring without an inner border or clipping', async ({ page }) => {
  await page.goto('/explore')
  const input = page.locator('main .search-bar input')
  await input.focus()
  await expect(input).toHaveCSS('box-shadow', 'none')
  await expect(input).toHaveCSS('outline-style', 'none')
  await expect(input.locator('..')).toHaveCSS('outline-style', 'solid')
  await input.fill('ciudad'); await input.press('Enter')
  await expect(page).toHaveURL(/q=ciudad/)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('circular image reveal uses entry point, resets after history, and respects touch keyboard and reduced motion', async ({ page, isMobile }, testInfo) => {
  await page.goto('/')
  const image = page.locator('.featured-article__image'), grey = image.locator('.reading-thumbnail__grey'), color = image.locator('.reading-thumbnail__color')
  await image.scrollIntoViewIfNeeded()
  await expect(grey).toHaveCSS('filter', 'grayscale(1)')
  await expect(color).toHaveCSS('opacity', '0')
  await expect(grey).toHaveCSS('transform', 'none')
  if (!isMobile) {
    const box = await image.boundingBox()
    await page.mouse.move(box.x - 8, box.y + 30)
    await page.mouse.move(box.x + 1, box.y + 30)
    await expect(image).toHaveAttribute('data-revealed', 'true')
    const clip = await color.evaluate((element) => { const animation = element.getAnimations()[0]; animation.pause(); animation.currentTime = 100; return getComputedStyle(element).clipPath })
    expect(clip).toMatch(/circle\(.+ at 1px 30px\)/)
    await page.screenshot({ path: testInfo.outputPath('circular-reveal.png') })
    await color.evaluate((element) => element.getAnimations()[0].finish())
    await page.mouse.move(0, 0)
    await expect(color).toHaveCSS('opacity', '0')
  }
  await image.click()
  await expect(page.locator('.article-page__hero')).toHaveCSS('filter', 'none')
  await page.mouse.move(0, 0); await page.goBack()
  await expect(image).toHaveAttribute('data-revealed', 'false')
  await expect(color).toHaveCSS('opacity', '0')
  await page.locator('.featured-article .text-link').focus()
  await page.keyboard.press('Tab')
  await expect(image).toBeFocused()
  await expect(image).toHaveCSS('outline-style', 'solid')
  await expect(image).toHaveAttribute('data-revealed', 'true')
  await page.keyboard.press('Tab'); await expect(color).toHaveCSS('opacity', '0')
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await image.scrollIntoViewIfNeeded()
  if (!isMobile) {
    await image.hover()
    await expect(color).toHaveCSS('opacity', '1')
    expect(await color.evaluate((node) => node.getAnimations().length)).toBe(0)
  }
})
